language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
jobs:
  include:
    - stage: test
      script:
        - flake8 .
        - coverage run --source=. -m unittest discover -s tests/
        - coverage report -m
